baseURL: "https://www.example.com/"
theme: "up-business-theme"
languageCode: "en-us"

title: Dev Factory

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Dev Factory"
  description: "We specialize in providing services to desing websites, applications, build and maintain business for customers."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "Montpellier - France"

  contact:
    - "contact@devfactory.fr"
    - "07 79 82 63 75"

  copyright: "© 2022 Dev Factory All Rights Reserved"

  postProcess: false

menus:
  main:
    - name: "Home"
      url: "/"
      weight: 1

    - name: "ECommerce"
      url: "/#"
      weight: 2

    - name: "Landing Page"
      url: "/#"
      weight: 3

    - name: "SEO"
      url: "/#"
      weight: 4

    - name: "Pricing"
      url: "/#"
      weight: 5

  buttons:
    - name: "Book a call"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/"
      weight: 1

    - name: "Ecommerce"
      url: "/#"
      weight: 2

    - name: "Landing Page"
      url: "/#"
      weight: 3

    - name: "SEO"
      url: "/#"
      weight: 4

    - name: "Pricing"
      url: "/#"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
